// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type netprobeConnAttrV struct {
	_    structs.HostLayout
	Pid  uint32
	Pad  uint32
	TsNs uint64
}

// loadNetprobe returns the embedded CollectionSpec for netprobe.
func loadNetprobe() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NetprobeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load netprobe: %w", err)
	}

	return spec, err
}

// loadNetprobeObjects loads netprobe and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*netprobeObjects
//	*netprobePrograms
//	*netprobeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadNetprobeObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadNetprobe()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// netprobeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netprobeSpecs struct {
	netprobeProgramSpecs
	netprobeMapSpecs
	netprobeVariableSpecs
}

// netprobeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netprobeProgramSpecs struct {
	KprobeTcpConnect       *ebpf.ProgramSpec `ebpf:"kprobe_tcp_connect"`
	KprobeTcpSendmsg       *ebpf.ProgramSpec `ebpf:"kprobe_tcp_sendmsg"`
	KprobeUdpSendmsg       *ebpf.ProgramSpec `ebpf:"kprobe_udp_sendmsg"`
	KretprobeInetCskAccept *ebpf.ProgramSpec `ebpf:"kretprobe_inet_csk_accept"`
	KretprobeTcpRecvmsg    *ebpf.ProgramSpec `ebpf:"kretprobe_tcp_recvmsg"`
	KretprobeUdpRecvmsg    *ebpf.ProgramSpec `ebpf:"kretprobe_udp_recvmsg"`
}

// netprobeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netprobeMapSpecs struct {
	BytesRx         *ebpf.MapSpec `ebpf:"bytes_rx"`
	BytesTx         *ebpf.MapSpec `ebpf:"bytes_tx"`
	ConnAttribution *ebpf.MapSpec `ebpf:"conn_attribution"`
}

// netprobeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netprobeVariableSpecs struct {
}

// netprobeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadNetprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type netprobeObjects struct {
	netprobePrograms
	netprobeMaps
	netprobeVariables
}

func (o *netprobeObjects) Close() error {
	return _NetprobeClose(
		&o.netprobePrograms,
		&o.netprobeMaps,
	)
}

// netprobeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadNetprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type netprobeMaps struct {
	BytesRx         *ebpf.Map `ebpf:"bytes_rx"`
	BytesTx         *ebpf.Map `ebpf:"bytes_tx"`
	ConnAttribution *ebpf.Map `ebpf:"conn_attribution"`
}

func (m *netprobeMaps) Close() error {
	return _NetprobeClose(
		m.BytesRx,
		m.BytesTx,
		m.ConnAttribution,
	)
}

// netprobeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadNetprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type netprobeVariables struct {
}

// netprobePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadNetprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type netprobePrograms struct {
	KprobeTcpConnect       *ebpf.Program `ebpf:"kprobe_tcp_connect"`
	KprobeTcpSendmsg       *ebpf.Program `ebpf:"kprobe_tcp_sendmsg"`
	KprobeUdpSendmsg       *ebpf.Program `ebpf:"kprobe_udp_sendmsg"`
	KretprobeInetCskAccept *ebpf.Program `ebpf:"kretprobe_inet_csk_accept"`
	KretprobeTcpRecvmsg    *ebpf.Program `ebpf:"kretprobe_tcp_recvmsg"`
	KretprobeUdpRecvmsg    *ebpf.Program `ebpf:"kretprobe_udp_recvmsg"`
}

func (p *netprobePrograms) Close() error {
	return _NetprobeClose(
		p.KprobeTcpConnect,
		p.KprobeTcpSendmsg,
		p.KprobeUdpSendmsg,
		p.KretprobeInetCskAccept,
		p.KretprobeTcpRecvmsg,
		p.KretprobeUdpRecvmsg,
	)
}

func _NetprobeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed netprobe_x86_bpfel.o
var _NetprobeBytes []byte
