{{- if or .Values.apiToken .Values.postgres.url -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datawatch.fullname" . }}-secrets
  labels:
    {{- include "datawatch.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- if .Values.apiToken }}
  DATAWATCH_API_TOKEN: {{ .Values.apiToken | quote }}
{{- end }}
{{- if .Values.postgres.url }}
  DATAWATCH_POSTGRES_URL: {{ .Values.postgres.url | quote }}
{{- end }}
{{- end -}}

{{- if and .Values.tls.enabled (not .Values.tls.existingSecret) (and .Values.tls.cert .Values.tls.key) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datawatch.fullname" . }}-tls
  labels:
    {{- include "datawatch.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.cert | b64enc | quote }}
  tls.key: {{ .Values.tls.key | b64enc | quote }}
{{- end }}
