{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "datawatch.serviceAccountName" . }}
  labels:
    {{- include "datawatch.labels" . | nindent 4 }}
{{- end -}}
