// Package alerts provides a persistent store for system-level alerts
// generated by session filters and other internal components.
package alerts

import (
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"sync"
	"time"

	"github.com/dmz006/datawatch/internal/secfile"
)

// Level classifies the severity of an alert.
type Level string

const (
	LevelInfo  Level = "info"
	LevelWarn  Level = "warn"
	LevelError Level = "error"
)

// Alert is a single system notification.
type Alert struct {
	ID        string    `json:"id"`
	Level     Level     `json:"level"`
	Title     string    `json:"title"`
	Body      string    `json:"body"`
	SessionID string    `json:"session_id,omitempty"`
	Read      bool      `json:"read"`
	CreatedAt time.Time `json:"created_at"`
}

// Store is a persistent, thread-safe alert store.
type Store struct {
	mu        sync.Mutex
	path      string
	encKey    []byte
	alerts    []*Alert
	listeners []func(*Alert)
}

// NewStore creates a new Store backed by the given file path (no encryption).
// If the file does not exist it is created on first write.
func NewStore(path string) (*Store, error) {
	return newStoreWithKey(path, nil)
}

// NewStoreEncrypted creates an alert Store with AES-256-GCM encryption at rest.
func NewStoreEncrypted(path string, key []byte) (*Store, error) {
	return newStoreWithKey(path, key)
}

func newStoreWithKey(path string, key []byte) (*Store, error) {
	s := &Store{path: path, encKey: key}
	if err := s.load(); err != nil && !os.IsNotExist(err) {
		return nil, fmt.Errorf("load alert store: %w", err)
	}
	return s, nil
}

func (s *Store) load() error {
	data, err := secfile.ReadFile(s.path, s.encKey)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &s.alerts)
}

func (s *Store) save() error {
	data, err := json.MarshalIndent(s.alerts, "", "  ")
	if err != nil {
		return err
	}
	return secfile.WriteFile(s.path, data, 0600, s.encKey)
}

// AddListener registers a callback invoked whenever a new alert is created.
func (s *Store) AddListener(fn func(*Alert)) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.listeners = append(s.listeners, fn)
}

// Add creates a new alert and persists it. Returns the created alert.
func (s *Store) Add(level Level, title, body, sessionID string) *Alert {
	b := make([]byte, 4)
	rand.Read(b) //nolint:errcheck
	a := &Alert{
		ID:        hex.EncodeToString(b),
		Level:     level,
		Title:     title,
		Body:      body,
		SessionID: sessionID,
		Read:      false,
		CreatedAt: time.Now(),
	}
	s.mu.Lock()
	s.alerts = append(s.alerts, a)
	// Keep at most 500 alerts
	if len(s.alerts) > 500 {
		s.alerts = s.alerts[len(s.alerts)-500:]
	}
	s.save() //nolint:errcheck
	listeners := make([]func(*Alert), len(s.listeners))
	copy(listeners, s.listeners)
	s.mu.Unlock()

	for _, fn := range listeners {
		fn(a)
	}
	return a
}

// List returns all alerts (newest first).
func (s *Store) List() []*Alert {
	s.mu.Lock()
	defer s.mu.Unlock()
	out := make([]*Alert, len(s.alerts))
	for i, a := range s.alerts {
		cp := *a
		out[i] = &cp
	}
	// reverse: newest first
	for i, j := 0, len(out)-1; i < j; i, j = i+1, j-1 {
		out[i], out[j] = out[j], out[i]
	}
	return out
}

// UnreadCount returns the number of unread alerts.
func (s *Store) UnreadCount() int {
	s.mu.Lock()
	defer s.mu.Unlock()
	n := 0
	for _, a := range s.alerts {
		if !a.Read {
			n++
		}
	}
	return n
}

// MarkRead marks a single alert as read.
func (s *Store) MarkRead(id string) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	for _, a := range s.alerts {
		if a.ID == id {
			a.Read = true
			return s.save()
		}
	}
	return fmt.Errorf("alert %q not found", id)
}

// MarkAllRead marks all alerts as read.
func (s *Store) MarkAllRead() {
	s.mu.Lock()
	defer s.mu.Unlock()
	for _, a := range s.alerts {
		a.Read = true
	}
	s.save() //nolint:errcheck
}
