#!/usr/bin/env python3
"""Generate .trivyignore and docs/security-review.md's container-scanning
table from security/accepted-risks.yml. Run after any edit to the
registry; `make security-registry-gen` runs the lint then this. CI checks both
generated files are in sync with the registry (regenerate-and-diff).

Only `kind: container` entries are emitted here -- `dependency`,
`code-scanning` and `bundled-js` entries belong to other tooling
(govulncheck/gosec's docs/security-review.md sections, gitleaks, etc.),
not Trivy's ignorefile.
"""
import sys

try:
    import yaml
except ImportError:
    sys.exit("PyYAML is required: pip install pyyaml")

REGISTRY_PATH = "security/accepted-risks.yml"
TRIVYIGNORE_PATH = ".trivyignore"
SECURITY_REVIEW_PATH = "docs/security-review.md"

BEGIN_MARK = "<!-- BEGIN GENERATED: security/accepted-risks.yml container entries (scripts/gen_trivyignore.py) -->"
END_MARK = "<!-- END GENERATED -->"


def load_entries():
    with open(REGISTRY_PATH) as f:
        data = yaml.safe_load(f)
    return [e for e in (data or {}).get("entries") or [] if e.get("kind") == "container"]


def cve_id(entry):
    return entry["id"].split("/", 1)[1]


def gen_trivyignore(entries):
    lines = [
        "# Container image CVE exceptions.",
        "# GENERATED by scripts/gen_trivyignore.py from security/accepted-risks.yml --",
        "# do not hand-edit. Edit the registry and regenerate.",
        "# Security acceptance standard (operator, 2026-10-08; shared with",
        "# datawatch-app, dmz006/datawatch#197). See security/accepted-risks.yml's",
        "# header for the schema, and scripts/check_accepted_risks.py for the lint.",
        "",
    ]
    # Group consecutive entries sharing (package, analysis, reason) into one
    # comment block, same shape .trivyignore has always used.
    groups = []
    for e in entries:
        key = (e["package"], e["impact"]["analysis"], e["reason"])
        if groups and groups[-1][0] == key:
            groups[-1][1].append(e)
        else:
            groups.append((key, [e]))

    for (package, analysis, reason), group in groups:
        images = sorted(set(im for e in group for im in e.get("images") or []))
        ids = ", ".join(cve_id(e) for e in group)
        severities = sorted(set(e["severity"] for e in group))
        traced_note = ""
        for e in group:
            if e["impact"]["traced"]:
                traced_note = f" TRACED: {e['impact']['method']}"
        lines.append(f"# {package} -- {ids}")
        lines.append(f"# severity: {'/'.join(severities)}" + (f"; images: {', '.join(images)}" if images else ""))
        for chunk in wrap(analysis, 78):
            lines.append(f"# {chunk}")
        for chunk in wrap(reason, 78):
            lines.append(f"# {chunk}")
        if traced_note:
            for chunk in wrap(traced_note.strip(), 78):
                lines.append(f"# {chunk}")
        for e in group:
            lines.append(cve_id(e))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def wrap(text, width):
    words = text.split()
    out, cur = [], ""
    for w in words:
        if cur and len(cur) + 1 + len(w) > width:
            out.append(cur)
            cur = w
        else:
            cur = f"{cur} {w}" if cur else w
    if cur:
        out.append(cur)
    return out


def gen_security_review_table(entries):
    lines = [
        "| CVE | Package | Severity | Images | Traced | Expires | Reason |",
        "|---|---|---|---|---|---|---|",
    ]
    for e in sorted(entries, key=cve_id):
        images = ", ".join(e.get("images") or []) or "-"
        traced = "yes" if e["impact"]["traced"] else "no"
        lines.append(
            f"| {cve_id(e)} | `{e['package']}` | {e['severity']} | {images} | {traced} | {e['expires']} | {e['reason'][:80]}{'...' if len(e['reason']) > 80 else ''} |"
        )
    n_traced = sum(1 for e in entries if e["impact"]["traced"])
    summary = f"\n**{len(entries)} suppressed container CVEs across {len({im for e in entries for im in e.get('images') or []})} images, {n_traced} independently traced.**\n"
    return summary + "\n" + "\n".join(lines) + "\n"


def splice_security_review(table_md):
    with open(SECURITY_REVIEW_PATH) as f:
        content = f.read()
    if BEGIN_MARK not in content:
        sys.exit(f"{SECURITY_REVIEW_PATH}: missing {BEGIN_MARK!r} marker -- add it once by hand under '## Container image scanning' before running this generator.")
    pre, rest = content.split(BEGIN_MARK, 1)
    _, post = rest.split(END_MARK, 1)
    new_content = pre + BEGIN_MARK + "\n" + table_md + "\n" + END_MARK + post
    with open(SECURITY_REVIEW_PATH, "w") as f:
        f.write(new_content)


def main():
    entries = load_entries()
    with open(TRIVYIGNORE_PATH, "w") as f:
        f.write(gen_trivyignore(entries))
    splice_security_review(gen_security_review_table(entries))
    print(f"generated {TRIVYIGNORE_PATH} and spliced {SECURITY_REVIEW_PATH} from {len(entries)} container entries")


if __name__ == "__main__":
    main()
